name: MASA
version: 1.0
main: com.theaudiobros.masa.MASA
load: startup
commands:
   unloadworld:
     description: Unloads the world.
     default: op
   tpworld:
     description: Tps
     default: op
   loadSchem:
     description: Tps
     default: op
